name: Browser tests

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    browser-tests:
        name: "Browser tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'commerce'
            test-suite:  '--profile=browser --suite=__PACKAGE_NAME__ --config=vendor/__VENDOR_NAME__/__PACKAGE_NAME__/behat.yaml'
        secrets:
            SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
            SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
            TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
